branches:
  only:
    - master

# language: ruby
# rvm:
#   - "2.1.2"

install: 
  - mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
  - echo 'execute pathogen#infect()' >> ~/.vimrc
  - echo 'syntax on' >> ~/.vimrc
  - echo 'filetype plugin indent on' >> ~/.vimrc
  - cd ~/.vim/bunlde && git clone https://github.com/tpope/timl
script: 
  ls -ltr ~/.vim*

