branches:
  only:
    - master

language: ruby
rvm:
  - "2.1.2"

install: 
  - mkdir tmp
  - mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
  - echo 'execute pathogen#infect()' >> ~/.vimrc
  - echo 'syntax on' >> ~/.vimrc
  - echo 'filetype plugin indent on' >> ~/.vimrc
  - cd ~/.vim/bundle && git clone https://github.com/tpope/timl
script: 
  # Need to run vim with a source file that exits
  - ls -R

